openapi: 3.0.2
info:
  title: Process Platform Worker API
  description: |
    API for Process Platform manager nodes

  version: "1.0"

servers:
  - url: /process-worker/api

tags:
  - name: ForManager
    description: >
      Fetching logs, deleting process working directories, killing running processes

paths:
  /manager/info:
    get:
      tags:
        - ForManager
      summary: General info on worker state
      description: General info on worker state
      operationId: info
      responses:
        '200':
          description: General info on worker state
          content:
            application/json:
              schema:
                type: string
              example: {
                "workerStatus" : "UP",
                "state" : "IDLE",
                "message" : "Worker is waiting for the next process.",
                "jvmAlive" : false
              }

  /manager/{processId}/log/out:
    get:
      tags:
        - ForManager
      summary: Returns process standard output logs
      description: Returns process standard output logs
      parameters:
        - name: processId
          in: path
          required: true
          description: Process id
          schema:
            type: string
            format: uuid
          example: 103cb713-b778-4370-8d58-f13bf4b276ec
        - name: fileName
          in: query
          required: false
          description: File name. Default "out.txt".
          schema:
            type: string
            default: "out.txt"
      responses:
        '200':
          description: Log provided
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Process logs not found for the given processId.

  /manager/{processId}/log/err:
    get:
      tags:
        - ForManager
      summary: Returns process error output logs
      description: Returns process error output logs
      parameters:
        - name: processId
          in: path
          required: true
          description: uuid procesu
          schema:
            type: string
            format: uuid
          example: 103cb713-b778-4370-8d58-f13bf4b276ec
        - name: fileName
          in: query
          required: false
          description: File name. Default "err.txt".
          schema:
            type: string
            default: "err.txt"
      responses:
        '200':
          description: Log provided
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Error logs not found for the given process id.

  /manager/{processId}/log/out/lines:
    get:
      tags:
        - ForManager
      summary: Získá standardní výstup ve formě řádklů
      description: Získá standardní výstup ve formě řádků
      parameters:
        - name: processId
          in: path
          required: true
          description: UUID procesu, pro který se získávají logy.
          schema:
            type: string
        - name: offset
          in: query
          description: Počáteční index, od kterého se začnou načítat řádky logu.
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          description: Maximální počet řádků logu, které se mají vrátit.
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: Úspěšně načtené logy procesu.
        '400':
          description: Neplatný požadavek, např. neplatný offset nebo limit.
        '404':
          description: Proces s daným UUID nebyl nalezen.

  /manager/{processId}/log/err/lines:
    get:
      tags:
        - ForManager
      summary: Získá err výstup ve formě řádklů
      description: Získá err výstup ve formě řádků
      parameters:
        - name: processId
          in: path
          required: true
          description: UUID procesu, pro který se získávají logy.
          schema:
            type: string
        - name: offset
          in: query
          description: Počáteční index, od kterého se začnou načítat řádky logu.
          schema:
            type: integer
          example: 0
        - name: limit
          in: query
          description: Maximální počet řádků logu, které se mají vrátit.
          schema:
            type: integer
          example: 100
      responses:
        '200':
          description: Úspěšně načtené logy procesu.
        '400':
          description: Neplatný požadavek, např. neplatný offset nebo limit.
        '404':
          description: Proces s daným UUID nebyl nalezen.

  /manager/{processId}/directory:
    delete:
      tags:
        - ForManager
      summary: Deletes process working directory
      description: Deletes process working directory
      parameters:
        - name: processId
          in: path
          required: true
          description: Process id
          example: ed25ce29-2149-439d-85c4-cc5e516e3036
      responses:
        '200':
          description: Directory deleted or does not exist
          content:
            application/json:
              schema:
                type: string

  /manager/{pid}/kill:
    delete:
      tags:
        - ForManager
      summary: Kills running process
      description: Kills running process
      parameters:
        - name: pid
          in: path
          required: true
          description: PID of the running process
          example: 576
      responses:
        '200':
          description: Process killed
        '404':
          description: Process does not exist



