name: Release new version of Process platform

on:
  workflow_dispatch:
    inputs: 

jobs:
  build_jar:

    runs-on: ubuntu-latest
    environment: BUILD
    steps:

    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Set execute permission for gradlew
      run: chmod +x ./gradlew
      env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Show build.gradle contents
      run: cat build.gradle

    - name: Get project version from Gradle
      run: |
        VERSION=$(./gradlew printVersion -q)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TAG_NAME=v$VERSION" >> $GITHUB_ENV
        echo "RELEASE_NAME=Release v$VERSION" >> $GITHUB_ENV          
    
    - name: Build with Gradle
      run: ./gradlew build publish --info
      env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.USER }}
          TOKEN: ${{ secrets.PAS }}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        body: |
          Auto-generated release for version ${{ env.VERSION }}
        draft: true
        prerelease: false

